#!/usr/bin/env bash
# Install nginx on web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create a backup of the default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Configure Nginx to return "Hello World!" at the root
echo "
server {
    listen 80;
    server_name _;

    location / {
        add_header Content-Type text/plain;
        return 200 'Hello World!';
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Use sed to replace the line with a redirection configuration block
sudo sed -i '/location \/ {/a \
\
    location \/redirect_me { \
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; \
    } \
' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
