#!/usr/bin/env bash
# Install nginx on web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# Create a backup of the default Nginx configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Use sed to replace the line with a redirection configuration block
sudo sed -i '/location \/ {/a \
\
    location \/redirect_me { \
        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4; \
    } \
' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart # or use sudo service nginx restart
