#!/usr/bin/env bash
# A Bash script that sends a signal message to a running process
pid=$(pgrep -f 7-highlander)
if [ -n "$pid" ]; then
  kill -s SIGTERM "$pid"
  sleep 1

  if ps -p "$pid" > /dev/null; then
    kill -9 "$pid"
  fi
fi
