#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School
# and then Hi on a new line.
n=1
while [ $n -le 10 ]; do
	if ((n == 9)); then
		echo Hi
	else
		echo Best School
	fi
    n=$((n+1))
done
