#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=1
while [ $n -lt 10 ]
do
	if [ $n -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((n++))
done	
