#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
n=1
while [ $n -le 10 ]; do
	if [ $n == 4 ]; then
		echo "bad luck"
	elif [ $n == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n+1))
done
